// Mocks generated by Mockito 5.4.6 from annotations
// in melapay/test/features/wallets/domain/usecases/wallet_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:melapay/core/errors/failure.dart' as _i5;
import 'package:melapay/features/wallets/domain/entities/wallet.dart' as _i6;
import 'package:melapay/features/wallets/domain/repositories/wallet_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WalletRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalletRepository extends _i1.Mock implements _i3.WalletRepository {
  MockWalletRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Wallet>>> getWallets() =>
      (super.noSuchMethod(
            Invocation.method(#getWallets, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Wallet>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Wallet>>(
                    this,
                    Invocation.method(#getWallets, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Wallet>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Wallet>> getWallet(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getWallet, [id]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Wallet>>.value(
              _FakeEither_0<_i5.Failure, _i6.Wallet>(
                this,
                Invocation.method(#getWallet, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Wallet>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Transaction>>> getTransactions(
    String? walletId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactions, [walletId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.Transaction>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Transaction>>(
                    this,
                    Invocation.method(#getTransactions, [walletId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Transaction>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deposit(
    String? id,
    double? amount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deposit, [id, amount]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deposit, [id, amount]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> withdraw(
    String? id,
    double? amount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#withdraw, [id, amount]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#withdraw, [id, amount]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> transfer(
    String? fromId,
    String? toId,
    double? amount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#transfer, [fromId, toId, amount]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#transfer, [fromId, toId, amount]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
